import { Project } from '@/types/project'

// Using placeholder videos - replace with your own video URLs when ready
// These are reliable placeholder video URLs for development
export const projects: Project[] = [
  {
    id: '1',
    title: 'The World Needs Defenders',
    slug: 'the-world-needs-defenders',
    description: 'THE WORLD NEEDS DEFENDERS',
    longDescription: 'CYBERSECURITY PROS DON\'T GET STATUES, AWARDS, OR PARADES — BUT THEY SHOULD. PARTNERING WITH GRIZZLY, DARKTRACE TAPPED OUTLIER TO BRING ITS NEW GLOBAL BRAND PLATFORM, THE WORLD NEEDS DEFENDERS, TO LIFE THROUGH A CAMPAIGN THAT CELEBRATES THE PEOPLE WHO PROTECT OUR CONNECTED WORLD. THE CHALLENGE: TURN THE INVISIBLE WORK OF CYBERSECURITY INTO SOMETHING EPIC — A STORY WORTHY OF THE HEROES WHO KEEP THE DIGITAL WORLD SAFE.\n\nSHOT OVER THREE DAYS IN WARSAW, POLAND, THE CAMPAIGN FEATURES CLARK GREGG, THE DEFENDER\'S DEFENDER, AS OUR GUIDE THROUGH THE UNSEEN BATTLES FOUGHT IN CYBERSPACE. WITH MONUMENTAL VISUALS, CINEMATIC SCALE, AND REVERENT STORYTELLING, WE TRANSFORMED QUIET DEFENDERS INTO CELEBRATED CHAMPIONS — POSITIONING DARKTRACE NOT JUST AS THE TECHNOLOGY THEY RELY ON, BUT AS THE ALLY THAT GIVES THEM THE EDGE AGAINST WHATEVER COMES NEXT.',
    client: 'DARKTRACE',
    category: 'Campaign',
    tags: ['DIRECTION', 'CINEMATOGRAPHY', 'VFX', 'POST'],
    year: '2025',
    coverImage: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    videoPoster: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1920&h=1080&fit=crop',
    collaborators: ['GRIZZLY', 'CLARK GREGG'],
    featured: true,
    order: 1,
    projectUrl: 'https://example.com',
    media: [
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1920&h=1080&fit=crop',
        title: 'Hero Shot',
        description: 'Monumental visuals capturing the essence of cybersecurity defense.',
      },
      {
        type: 'video',
        url: '/got.mp4',
        title: 'Behind the Scenes',
        description: 'A look at the production process in Warsaw, Poland.',
      },
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&h=1080&fit=crop',
        title: 'Cinematic Scale',
        description: 'Reverent storytelling that transforms quiet defenders into celebrated champions.',
      },
    ],
  },
  {
    id: '2',
    title: 'Better Begins Now',
    slug: 'better-begins-now',
    description: 'Stunning visuals capturing the beauty of nature.',
    client: 'Netflix',
    category: 'Commercial',
    tags: ['commercial'],
    year: '2025',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 2,
    projectUrl: 'https://example.com',
  },
  {
    id: '3',
    title: 'Creative Motion',
    slug: 'creative-motion',
    description: 'Abstract motion graphics and visual effects.',
    client: 'Youtube',
    category: 'Video',
    tags: ['experiential', 'event'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 3,
    projectUrl: 'https://example.com',
  },
  {
    id: '4',
    title: 'City Lights',
    slug: 'city-lights',
    description: 'Time-lapse of cityscapes and urban life.',
    client: 'Audi',
    category: 'Video',
    tags: ['commercial', 'event'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 4,
    projectUrl: 'https://example.com',
  },
  {
    id: '5',
    title: 'Ocean Waves',
    slug: 'ocean-waves',
    description: 'Serene ocean scenes and coastal beauty.',
    client: 'Ford',
    category: 'Video',
    tags: ['experiential'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 5,
    projectUrl: 'https://example.com',
  },
  {
    id: '6',
    title: 'Mountain Peaks',
    slug: 'mountain-peaks',
    description: 'Epic mountain landscapes and adventure.',
    client: 'Paramount',
    category: 'Video',
    tags: ['commercial'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 6,
    projectUrl: 'https://example.com',
  },
  {
    id: '7',
    title: 'Urban Exploration',
    slug: 'urban-exploration',
    description: 'A cinematic journey through urban landscapes.',
    client: 'Syfy',
    category: 'Video',
    tags: ['experiential'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 7,
    projectUrl: 'https://example.com',
  },
  {
    id: '8',
    title: 'Creative Vision',
    slug: 'creative-vision',
    description: 'Innovative storytelling and visual design.',
    client: 'Lenovo',
    category: 'Video',
    tags: ['commercial'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 8,
    projectUrl: 'https://example.com',
  },
  {
    id: '9',
    title: 'Next Generation',
    slug: 'next-generation',
    description: 'Pushing boundaries of creative expression.',
    client: 'Nickolodeon',
    category: 'Video',
    tags: ['experiential', 'event'],
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    videoUrl: '/got.mp4',
    thumbnailVideo: '/got.mp4',
    featured: true,
    order: 9,
    projectUrl: 'https://example.com',
  },
]

export function getProjects(): Project[] {
  return projects.sort((a, b) => (a.order || 0) - (b.order || 0))
}

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug)
}

export function getFeaturedProjects(): Project[] {
  return projects.filter((project) => project.featured).sort((a, b) => (a.order || 0) - (b.order || 0))
}
